logging:
  level: INFO
  appenders:
    - type: console
#      layout:
#        type: json

  loggers:
    nl.knaw.huygens.lobsang: DEBUG

server:
  requestLog:
    appenders:
    - type: console
      layout:
        type: access-json