logging:
  level: INFO
  appenders:
    - type: console
#      layout:
#        type: json

  loggers:
    nl.knaw.huygens.lobsang: DEBUG
    nl.knaw.huygens.lobsang.resources: TRACE

server:
  requestLog:
    appenders:
    - type: console
      layout:
        type: access-json

knownCalendars:
- name: default
  class: nl.knaw.huygens.lobsang.core.converters.JulianConverter
- name: Gregorian
  class: nl.knaw.huygens.lobsang.core.converters.GregorianConverter
- name: Julian
  class: nl.knaw.huygens.lobsang.core.converters.JulianConverter
#- name: roman
#  class: nl.knaw.huygens.lobsang.core.converters.RomanConverter

locationInfo:
  - location: Austria, Bohemia
    calendars:
    - type: Julian
      end: 1584-01-06
    - type: Gregorian
      start: 1584-01-17
  - location: Austria, Brixen, Salzburg and Tyrol
    calendars:
    - type: Julian
      end: 1583-10-05
    - type: Gregorian
      start: 1583-10-16
  - location: Dutch Republic, Gelderland
    calendars:
    - type: Gregorian
      start: 1700-07-12
  - location: Dutch Republic, Friesland and Groningen
    calendars:
    - type: Julian
      end: 1700-12-31
    - type: Gregorian
      start: 1701-01-12
  - location: Groningen (City)
    calendars:
    - type: Julian
      end: 1583-02-28
    - type: Gregorian
      start: 1583-03-11
      end: 1594-11-19
    - type: Julian
      start: 1594-11-10
      end: 1699-12-31
    - type: Gregorian
      start: 1700-01-01
