logging:
  level: INFO
  appenders:
    - type: console
#      layout:
#        type: json

  loggers:
    nl.knaw.huygens.lobsang: DEBUG
    nl.knaw.huygens.lobsang.resources: TRACE

server:
  requestLog:
    appenders:
    - type: console
      layout:
        type: access-json

locationInfo:
- location: Austria, Bohemia
  calendars:
  - type: gregorian
    start: 1584-01-17
- location: Austria, Brixen, Salzburg and Tyrol
  calendars:
  - type: gregorian
    start: 1583-10-16
- location: Dutch Republic, Gelderland
  calendars:
  - type: gregorian
    start: 1700-07-12
- location: Groningen (City)
  calendars:
  - type: gregorian
    start: 1583-03-11
  - type: julian
    start: 1594-11-10
  - type: gregorian
    start: 1700-01-01
